name: Linting

on: [push, pull_request]

env:
  CRATE_NAME: precious
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Check that code is lint clean using precious
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Cargo home
        uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        with:
          command: cache
      - name: Install Rust stable
        uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        with:
          command: install-rustup
          toolchain: stable
          override: true
      - name: Configure Git
        run: |
          git config --global user.email "jdoe@example.com"
          git config --global user.name "J. Doe"
      - name: Run install-dev-tools.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          mkdir $HOME/bin
          ./dev/bin/install-dev-tools.sh
      - name: Run precious
        run: |
          PATH=$PATH:$HOME/bin precious lint -a
